apiVersion: v1
kind: Service
metadata:
  name: sriov-network-metrics-exporter-service
  namespace: {{.Namespace}}
  annotations:
    prometheus.io/target: "true"
    {{- if eq .ClusterType "openshift" }}
    service.beta.openshift.io/serving-cert-secret-name: {{ .MetricsExporterSecretName }}
    {{- end }}
  labels:
    name: sriov-network-metrics-exporter-service
spec:
  selector:
    app: sriov-network-metrics-exporter
  ports:
    - protocol: TCP
      name: sriov-network-metrics
      port: {{ .MetricsExporterPort }}
      targetPort: {{ .MetricsExporterPort }}
