---
apiVersion: v1
kind: Service
metadata:
  name: operator-webhook-service
  namespace: {{.Namespace}}
  annotations:
    {{- if eq .ClusterType "openshift" }}
    service.alpha.openshift.io/serving-cert-secret-name: operator-webhook-service
    {{- end }}
spec:
  ports:
  - port: 443
    targetPort: 6443
  selector:
    app: operator-webhook
