updates:
  - file: "stable/sriov-network-operator.clusterserviceversion.yaml" # relative to this file
    update_list:
    # replace metadata.name value
    - search: "sriov-network-operator.v{MAJOR}.{MINOR}.0"
      replace: "sriov-network-operator.{FULL_VER}"
    - search: "version: {MAJOR}.{MINOR}.0"
      replace: "version: {FULL_VER}"
    - search: "olm.skipRange: '>=4.3.0-0 <{MAJOR}.{MINOR}.0'"
      replace: "olm.skipRange: '>=4.3.0-0 <{FULL_VER}'"
  - file: "sriov-network-operator.package.yaml"
    update_list:
    - search: "currentCSV: sriov-network-operator.v{MAJOR}.{MINOR}.0"
      replace: "currentCSV: sriov-network-operator.{FULL_VER}"
