---
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: policy-1
spec:
  resourceName: intelnics
  nodeSelector:
    feature.node.kubernetes.io/network-sriov.capable: "true"
  priority: 99
  mtu: 9000
  numVfs: 6
  nicSelector:
    vendor: "8086"
    rootDevices: ['0000:86:00.1',]
  deviceType: vfio-pci
---
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: policy-2
spec:
  resourceName: intelx700nicsgtp
  nodeSelector:
    feature.node.kubernetes.io/network-sriov.capable: "true"
  priority: 99
  mtu: 9000
  numVfs: 6
  ddpUrl: "https://downloadmirror.intel.com/27587/eng/gtp.zip"
  nicSelector:
    vendor: "8086"
    rootDevices: ['0000:86:00.0',]
  deviceType: vfio-pci
---
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: policy-3
spec:
  resourceName: mlxnics
  nodeSelector:
    feature.node.kubernetes.io/network-sriov.capable: "true"
  priority: 99
  mtu: 9000
  numVfs: 16
  nicSelector:
    vendor: "15b3"
    rootDevices: ['0000:02:00.0', '0000:02:00.1']
  deviceType: netdevice
  isRdma: true
---
# Changing mtu for Mellanox IB NICs is out of scope
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: mlnx-ib-nics
  namespace: sriov-network-operator
spec:
  resourceName: mlxibnics
  nodeSelector:
    feature.node.kubernetes.io/network-ib-sriov.capable: "true"
  priority: 99
  numVfs: 16
  nicSelector:
    vendor: "15b3"
    rootDevices: ['0000:02:00.0', '0000:02:00.1']
  deviceType: netdevice
  isRdma: true
  linkType: IB
