apiVersion: sriovnetwork.openshift.io/v1
kind: SriovOperatorConfig
metadata:
  name: default
spec:
  # Add fields here
  enableInjector: true
  enableOperatorWebhook: true
  configDaemonNodeSelector: {}
