apiVersion: apps/v1
kind: Deployment
metadata:
  name: sriov-network-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sriov-network-operator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: sriov-network-operator
      annotations:
        openshift.io/required-scc: restricted-v2
    spec:
      affinity:
        nodeAffinity:
          # In the context of Hypershift, the SR-IOV network
          # Operator is deployed on Nodepools which are labeled
          # as workers. So we relax the node affinity to prefer
          # masters/control-plane when possible otherwise we
          # schedule where it's possible.
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: "node-role.kubernetes.io/master"
                    operator: Exists
            - weight: 1
              preference:
                matchExpressions:
                  - key: "node-role.kubernetes.io/control-plane"
                    operator: Exists
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
      serviceAccountName: sriov-network-operator
      priorityClassName: "system-node-critical"
      containers:
        - name: sriov-network-operator
          # Replace this with the built image name
          image: $SRIOV_NETWORK_OPERATOR_IMAGE
          command:
          - sriov-network-operator
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SRIOV_CNI_IMAGE
              value: $SRIOV_CNI_IMAGE
            - name: SRIOV_INFINIBAND_CNI_IMAGE
              value: $SRIOV_INFINIBAND_CNI_IMAGE
            - name: OVS_CNI_IMAGE
              value: $OVS_CNI_IMAGE
            - name: RDMA_CNI_IMAGE
              value: $RDMA_CNI_IMAGE
            - name: SRIOV_DEVICE_PLUGIN_IMAGE
              value: $SRIOV_DEVICE_PLUGIN_IMAGE
            - name: NETWORK_RESOURCES_INJECTOR_IMAGE
              value: $NETWORK_RESOURCES_INJECTOR_IMAGE
            - name: OPERATOR_NAME
              value: sriov-network-operator
            - name: SRIOV_NETWORK_CONFIG_DAEMON_IMAGE
              value: $SRIOV_NETWORK_CONFIG_DAEMON_IMAGE
            - name: SRIOV_NETWORK_WEBHOOK_IMAGE
              value: $SRIOV_NETWORK_WEBHOOK_IMAGE
            - name: METRICS_EXPORTER_IMAGE
              value: $METRICS_EXPORTER_IMAGE
            - name: METRICS_EXPORTER_KUBE_RBAC_PROXY_IMAGE
              value: $METRICS_EXPORTER_KUBE_RBAC_PROXY_IMAGE
            - name: METRICS_EXPORTER_PROMETHEUS_OPERATOR_ENABLED
              value: "$METRICS_EXPORTER_PROMETHEUS_OPERATOR_ENABLED"
            - name: METRICS_EXPORTER_PROMETHEUS_DEPLOY_RULES
              value: "$METRICS_EXPORTER_PROMETHEUS_DEPLOY_RULES"
            - name: METRICS_EXPORTER_PROMETHEUS_OPERATOR_SERVICE_ACCOUNT
              value: $METRICS_EXPORTER_PROMETHEUS_OPERATOR_SERVICE_ACCOUNT
            - name: METRICS_EXPORTER_PROMETHEUS_OPERATOR_NAMESPACE
              value: $METRICS_EXPORTER_PROMETHEUS_OPERATOR_NAMESPACE
            - name: RESOURCE_PREFIX
              value: $RESOURCE_PREFIX
            - name: DEV_MODE
              value: "$DEV_MODE"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: RELEASE_VERSION
              value: 4.3.0
            - name: SRIOV_CNI_BIN_PATH
              value: $CNI_BIN_PATH
            - name: CLUSTER_TYPE
              value: $CLUSTER_TYPE
            - name: ADMISSION_CONTROLLERS_CERTIFICATES_OPERATOR_SECRET_NAME
              value: $ADMISSION_CONTROLLERS_CERTIFICATES_OPERATOR_SECRET_NAME
            - name: ADMISSION_CONTROLLERS_CERTIFICATES_INJECTOR_SECRET_NAME
              value: $ADMISSION_CONTROLLERS_CERTIFICATES_INJECTOR_SECRET_NAME
            - name: ADMISSION_CONTROLLERS_CERTIFICATES_CERT_MANAGER_ENABLED
              value: "$ADMISSION_CONTROLLERS_CERTIFICATES_CERT_MANAGER_ENABLED"
            - name: ADMISSION_CONTROLLERS_CERTIFICATES_OPERATOR_CA_CRT
              value: $ADMISSION_CONTROLLERS_CERTIFICATES_OPERATOR_CA_CRT
            - name: ADMISSION_CONTROLLERS_CERTIFICATES_INJECTOR_CA_CRT
              value: $ADMISSION_CONTROLLERS_CERTIFICATES_INJECTOR_CA_CRT
            - name: METRICS_EXPORTER_SECRET_NAME
              value: $METRICS_EXPORTER_SECRET_NAME
            - name: METRICS_EXPORTER_PORT
              value: "$METRICS_EXPORTER_PORT"
