kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sriov-network-operator
  namespace: sriov-network-operator
subjects:
- kind: ServiceAccount
  name: sriov-network-operator
roleRef:
  kind: Role
  name: sriov-network-operator
  apiGroup: rbac.authorization.k8s.io
