name: "Push images on merge to master"

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}
  BUILD_PLATFORMS: linux/amd64,linux/arm64,linux/ppc64le

on:
  push:
    branches:
      - master

jobs:
  build-and-push-image-operator:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Build and push sriov-network-operator
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: ${{ env.BUILD_PLATFORMS }}
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          file: ./Dockerfile

  build-and-push-image-config-daemon:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}-config-daemon

      - name: Build and push sriov-network-operator-config-daemon
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: ${{ env.BUILD_PLATFORMS }}
          tags: |
            ${{ env.IMAGE_NAME }}-config-daemon:latest
            ${{ env.IMAGE_NAME }}-config-daemon:${{ github.sha }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          file: ./Dockerfile.sriov-network-config-daemon

  build-and-push-image-webhook:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}-webhook

      - name: Build and push sriov-network-operator-webhook
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: ${{ env.BUILD_PLATFORMS }}
          tags: |
            ${{ env.IMAGE_NAME }}-webhook:latest
            ${{ env.IMAGE_NAME }}-webhook:${{ github.sha }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          file: ./Dockerfile.webhook
